#!/usr/bin/env bash

SEMEDDB_DOWNLOAD_PATH=https://skr3.nlm.nih.gov/SemMedDB/download/
SEMEDDB_VERSION=31
SEMMEDB_FILE_PREFIX=semmedVER${SEMEDDB_VERSION}
SEMEDDB_PUBMED_VERSION=to12312017

SEMMEDDB_PREDICATION_FILE=${SEMMEDB_FILE_PREFIX}_R_PREDICATION_${SEMEDDB_PUBMED_VERSION}
SEMMEDDB_PREDICATION_ARCHIVE=${SEMMEDDB_PREDICATION_FILE}.sql.gz
SEMMEDDB_PREDICATION_DOWNLOAD=${SEMEDDB_DOWNLOAD_PATH}${SEMMEDDB_PREDICATION_ARCHIVE}
SEMMEDDB_PREDICATION_CSV=${SEMMEDDB_PREDICATION_FILE}.csv

echo "SemMedDb Predication Variables"
echo Archive: ${SEMMEDDB_PREDICATION_ARCHIVE}
echo Download: ${SEMMEDDB_PREDICATION_DOWNLOAD}
echo CSV: ${SEMMEDDB_PREDICATION_CSV}
